# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTIAPZzQ5oyJU4qq4xywJsAbvt7dSyGD
"""

import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Veri setini oku
data = pd.read_csv("/content/USD_TRY_Exchange_Rate.csv", parse_dates=["Tarih"], dayfirst=True)

# Tarih sütununu yıl, ay ve gün olarak ayır
data["Yıl"] = data["Tarih"].dt.year
data["Ay"] = data["Tarih"].dt.month
data["Gün"] = data["Tarih"].dt.day

# Virgül işaretlerini noktaya çevir ve veri tipini float yap
for column in data.columns:
    if data[column].dtype == "object":
        data[column] = data[column].str.replace(',', '.')
        if column == "Fark %":
            data[column] = data[column].str.rstrip('%')
        data[column] = data[column].astype(float)

# Model için kullanılacak özellikler ve hedefler
features = ["Yıl", "Ay", "Gün"]
target_columns = ["Açılış", "Yüksek", "Düşük", "Fark %"]

models = {}
for target in target_columns:
    # Feature ve label'ları ayır
    X = data[features]
    y = data[target]

    # Veri setini eğitim ve test setlerine ayır
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Model seçimi ve eğitimi
    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)

    # Model performansını değerlendirme
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    train_rmse = mean_squared_error(y_train, train_pred, squared=False)
    test_rmse = mean_squared_error(y_test, test_pred, squared=False)

    print(f"{target} - Eğitim seti RMSE:", train_rmse)
    print(f"{target} - Test seti RMSE:", test_rmse)

    models[target] = model


# Kullanıcıdan tarih al
input_date = input("Tahmin yapmak istediğiniz tarihi girin (gg.aa.yyyy): ")
input_date = pd.to_datetime(input_date, format="%d.%m.%Y")

# Girdi tarihi için özellikleri çıkar
input_features = {
    "Yıl": input_date.year,
    "Ay": input_date.month,
    "Gün": input_date.day
}

input_data = pd.DataFrame([input_features])

# Tahminleri yap ve sonuçları göster
predictions = {}
for target, model in models.items():
    predictions[target] = model.predict(input_data)[0]

print("Tahmin edilen değerler:")
print("Açılış:", predictions["Açılış"])
print("Yüksek:", predictions["Yüksek"])
print("Düşük:", predictions["Düşük"])
print("Fark %:", predictions["Fark %"])